### ISSUE TITLE
Underlying keymap issue

### ISSUE THREAD

**Issue by ko-pp** [st3r4g/wlanthy#11]
Hi,

I found a weird (and somewhat problematic, at least for me) behavior: on the first launch of wlanthy, it uses the keymap of the first keyboard I type on (fr-oss for the built-in keyboard and bepo for the external keyboard) but if I kill it (^C), I have to wait ~10-15 minutes or the keymap used by wlanthy will be qwerty (no other software seems to be impacted).

While I don’t really mind being restricted to the first keymap used on launch*, I would prefer being able to simply restart wlanthy when I un-/dock the laptop (and changing which physical keyboard I use) without waiting 10-15 minutes before being able to use it again.

Any idea on how to diagnose/fix this? :slightly_smiling_face: 

In case it helps:
- Sway v1.6.1
- VoidLinux
- Linux 5.12.17_1
- wlanthy from master (6cf315a) launched manually via foot 1.8.2

とにかく,wlanthyを生み出してありがとう! (apologies for any mistake, I have much to learn still :stuck_out_tongue:)

\* Obviously, it would be best if the underlying keymap could change on the fly but it would be more of a nice-to-have feature ^^

**Comment by st3r4g** [comment]
That is quite strange, especially the fact that it changes behavior with time...

> on the first launch of wlanthy, it uses the keymap of the first keyboard I type on

I tried to reproduce your configuration:
```
input "1:1:AT_Translated_Set_2_keyboard" {
	xkb_layout fr(oss)
}

input "6700:3620:SEM_USB_Keyboard" {
	xkb_layout fr(bepo)
}
```
but for me the layout used by wlanthy appears to be always qwerty (us layout):
```
$ swaymsg -t get_inputs | grep virtual -A9
    "identifier": "0:0:virtual_keyboard",
    "name": "virtual keyboard",
    "vendor": 0,
    "product": 0,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)"
  },
```
wlanthy isn't doing anything special, it just uses whatever layout it gets from the compositor via the `zwp_input_method_keyboard_grab_v2.keymap` event. I will have a look at how wlroots/sway decides what to send.

**Comment by ko-pp** [comment]
I get the same output for `swaymsg -t get_inputs | grep virtual -A9` as you, even when wlanthy is using the correct layout for my keyboard :confused: 

I tried removing L259-266 from main.c and I get the correct keymap each time + it also changes when I switch keyboard.
The problem is that the event is fired way too many times… ^^'

Maybe the keymap event from the seat’s keyboard could be used instead? From my testing, that event is only fired as needed but I’ve only been learning how to make a wayland client for two days (not even full time) so I might not be the right person to listen to x)

**Comment by st3r4g** [comment]
Could you try this patch:
```
diff --git a/main.c b/main.c
index d2afe50..5dc647a 100644
--- a/main.c
+++ b/main.c
@@ -259,10 +259,11 @@ static void handle_keymap(void *data,
 	/*
 	 * This is currently needed to avoid the keymap loop bug in sway
 	 */
-	static bool first_call = true;
-	if (!first_call)
-    		return;
-	first_call = false;
+	if (!(seat->xkb_keymap_string == NULL || strcmp(seat->xkb_keymap_string, str) != 0)) {
+		munmap(str, size);
+		close(fd);
+		return;
+	}
 
 	zwp_virtual_keyboard_v1_keymap(seat->virtual_keyboard, format, fd,
 								   size);

```
Simply save it as `patch` and `git apply patch`. It's still an ugly workaround to an issue in sway I believe, but should do the job for now.

**Comment by ko-pp** [comment]
It works!

Adding
```C
printf("Keymap: %s\n", xkb_keymap_layout_get_name(seat->xkb_keymap, 0));
```
line 280 (after the patch), I can see that the keymap is `English (US)` at first then changes according to the keyboard I use without being called when unnecessary :slightly_smiling_face: 

Also, `swaymsg -t get_inputs | grep virtual -A9`’s output changes:
```
    "identifier": "0:0:virtual_keyboard",
    "name": "virtual keyboard",
    "vendor": 0,
    "product": 0,
    "type": "keyboard",
    "xkb_layout_names": [
      "French (BEPO)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "French (BEPO)"
  },
```

Thank you :smiley_cat:

**Comment by st3r4g** [comment]
Perfect, I will push it to master. Thanks for reporting and testing!
