### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by rantlivelintkale** [st3r4g/wlanthy#12]
Hey, I'm trying to build this on FreeBSD but I get an error where meson complains that libanthyinput can't be found. I'm able to build `wlhangul` just fine, so I'm trying to find out if it is an issue with the `ja-anthy` package in FreeBSD.

Running `meson build/` gives me:
```
The Meson build system
Version: 0.59.1
Source dir: /usr/home/kallinen/code/wlanthy
Build dir: /usr/home/kallinen/code/wlanthy/build
Build type: native build
Project name: wlanthy
Project version: 0.0.0
C compiler for the host machine: cc (clang 11.0.1 "FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)")
C linker for the host machine: cc ld.lld 11.0.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Found pkg-config: /usr/local/bin/pkg-config (1.7.4)
Run-time dependency anthy found: YES 0.4

meson.build:29:1: ERROR: C shared or static library 'anthyinput' not found
```

[meson-log.txt](https://github.com/st3r4g/wlanthy/files/7188041/meson-log.txt)

**Comment by st3r4g** [comment]
From the log you attached, it seems that the linker cannot find the `libanthyinput.so` library, even though I see [here](https://cgit.freebsd.org/ports/tree/japanese/anthy/pkg-plist) that it should be provided by the FreeBSD package. So I'm not sure what's going on...

**Comment by rantlivelintkale** [comment]
Okay, I think I'm getting closer to the reason why the build fails, that is why `libanthyinput.so` is not found.

FreeBSD pulls anthy from here: https://salsa.debian.org/debian/anthy

This, I guess, is what Debian also uses for anthy as their source, and after trying to build on Debian I get the same error, where the linker can not find `libanthyinput.so`.

While on Arch and Alpine Linux, Anthy comes from here: https://osdn.net/projects/anthy/releases/37536

**Comment by st3r4g** [comment]
I am aware that there are two different sources for anthy, the original one and the debian one, which adds UTF-8 support. But both should provide `libanthyinput`. On debian, which splits packages a lot, you have to install `libanthyinput-dev` to have it.

Does `libanthyinput.so` exist in your linker path? (Probably `/lib/libanthyinput.so`)

By the way, if you use the UTF-8 sources you can also build with `-Dinput=custom` and `libanthyinput` is replaced by my own implementation. But that is not quite finished yet.

**Comment by rantlivelintkale** [comment]
Yeah, my bad, it compiles just fine on Debian.

`libanthyinput.so` is installed in `/usr/local/bin` since it is a port. `cc --print-search-dirs` tells me that the linker does not look for libraries in `/usr/local/bin`:

```
programs: =/usr/bin
libraries: =/usr/lib/clang/11.0.1:/usr/lib
```

If I build with `LDFLAGS="-L/usr/local/lib"` it finds `anthyinput.so` but after that it then fails to find `libiconv.so`, which I do have installed. Same with `-Dinput=custom`.

**Comment by rantlivelintkale** [comment]
Okay, I can get it to build now. Based on [this](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/277/diffs?commit_id=f57276d2ad584871b6fd9daf6f4eb7a5098ca8a0), I changed `dependency('libiconv')` to `cc.find_library('iconv')` in `meson.build`. I think this is related to `pkgconf` not finding `libiconv.so` on FreeBSD, but I do not why that would be the case.

**Comment by jbeich** [comment]
Add `-DLIBICONV_PLUG` to `CPPFLAGS` in order to make `/usr/local/include/iconv.h` pass through to `/usr/include/iconv.h`, eliminating `-liconv` dependency. If `libiconv` package is installed `-I/usr/local/include` (e.g., via `pkg-config --cflags wayland-client`) modifies how `<iconv.h>` is searched, making GNU libiconv appear before BSD iconv from libc. See also https://github.com/freebsd/freebsd-ports/commit/0052e743ef40759774eb918aa5180bcb21ea9cc1

**Comment by rantlivelintkale** [comment]
Okay, it builds now just fine without changing `build.meson`.

Thanks for the help!
